name = 'blazell-web'
compatibility_date ='2023-09-22'
account_id = '3551fbe61550836037b63f206e50bc73'

[placement]
mode = 'smart'

[vars]
REPLICACHE_KEY = 'lacf598018e5743a78248c89b3c05662b'
WORKER_URL = '[http://localhost:8787](http://localhost:8787/)'
CLERK_PUBLISHABLE_KEY=pk_test_YnVyc3Rpbmctd2FydGhvZy02MC5jbGVyay5hY2NvdW50cy5kZXYk
CLERK_SECRET_KEY=sk_test_UkiNd2Wwvo2wvA7XhrqURqNusu2OU9mmOZSOL12XNS
CLERK_SIGN_IN_URL='/sign-in'
CLERK_SIGN_UP_URL='/sign-up'
CLERK_AFTER_SIGN_IN_URL='/dashboard'
CLERK_AFTER_SIGN_UP_URL='/create-user'
PARTYKIT_HOST = 'blazell.lordpachimari.partykit.dev'

[env.development.vars]
REPLICACHE_KEY = 'lacf598018e5743a78248c89b3c05662b'
WORKER_URL = '[https://blazell-worker-development.pachimari.workers.dev](https://blazell-worker-development.pachimari.workers.dev/)'
CLERK_PUBLISHABLE_KEY=pk_test_YnVyc3Rpbmctd2FydGhvZy02MC5jbGVyay5hY2NvdW50cy5kZXYk
CLERK_SECRET_KEY=sk_test_UkiNd2Wwvo2wvA7XhrqURqNusu2OU9mmOZSOL12XNS
CLERK_SIGN_IN_URL='/sign-in'
CLERK_SIGN_UP_URL='/sign-up'
CLERK_AFTER_SIGN_IN_URL='/dashboard'
CLERK_AFTER_SIGN_UP_URL='/create-user'
PARTYKIT_HOST = 'blazell.lordpachimari.partykit.dev'

[env.production.vars]
REPLICACHE_KEY = 'lacf598018e5743a78248c89b3c05662b'
WORKER_URL = '[https://worker.blazell.com](https://worker.blazell.com/)'
CLERK_PUBLISHABLE_KEY=pk_test_YnVyc3Rpbmctd2FydGhvZy02MC5jbGVyay5hY2NvdW50cy5kZXYk
CLERK_SECRET_KEY=sk_test_UkiNd2Wwvo2wvA7XhrqURqNusu2OU9mmOZSOL12XNS
CLERK_SIGN_IN_URL='/sign-in'
CLERK_SIGN_UP_URL='/sign-up'
CLERK_AFTER_SIGN_IN_URL='/dashboard'
CLERK_AFTER_SIGN_UP_URL='/create-user'
PARTYKIT_HOST = 'blazell.lordpachimari.partykit.dev'